# Generated by Django 5.0.4 on 2024-12-09 02:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0005_rename_response_formresponsedata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2024, 12, 9)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formresponse',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
