# Generated by Django 5.0.4 on 2024-12-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0007_alter_formresponse_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
