# Generated by Django 5.0.4 on 2024-12-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0010_remove_template_name_template_templatename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='templatename',
            field=models.CharField(max_length=255),
        ),
    ]
