# Generated by Django 5.0.4 on 2024-12-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0011_alter_template_templatename'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Under Review', 'Under Review'), ('Completed', 'Completed'), ('Not Started', 'Not Started')], default='Not Started', max_length=50),
        ),
    ]
