# Generated by Django 5.0.4 on 2025-01-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0012_form_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formresponse',
            old_name='date',
            new_name='submit_date',
        ),
    ]
