# Generated by Django 5.0.4 on 2025-01-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0013_rename_date_formresponse_submit_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formresponse',
            old_name='submit_date',
            new_name='date_submitted',
        ),
    ]
