# Generated by Django 5.0.4 on 2024-12-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='type_of_consultation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
